spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: aslanoveltun28@gmail.com
    password: aprb sogn ijtf khqd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true